EscapeRoom/Controllers/HomeController.cs
using EscapeRoom.Data;
using EscapeRoom.Models;
using Microsoft.AspNetCore.Mvc;

namespace EscapeRoom.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "Home";

            return View();
        }

        public IActionResult Kontakt()
        {
            ViewData["Title"] = "Kontakt";
            return View();
        }

        public IActionResult DashBoard([FromServices] EscapeRoomContext context)
        {
            ViewData["Title"] = "Dashboard";

            ViewBag.Reservations = context.Reservations.ToList();
            ViewBag.Users = context.Users.ToList();
            ViewBag.Rooms = context.Rooms.ToList();
            return View();

        }

        public IActionResult SortedReservations([FromServices] EscapeRoomContext context)
        {
            ViewData["Title"] = "SortedReservations";

            ViewBag.Reservations = context.Reservations.ToList();
            ViewBag.Rooms = context.Rooms.ToList();
            return View();

        }

        
    }
}

EscapeRoom/Controllers/PokojeController.cs
using EscapeRoom.Data;
using Microsoft.AspNetCore.Mvc;

namespace EscapeRoom.Controllers
{
    public class PokojeController : Controller
    {
        private readonly EscapeRoomContext _context;

        public PokojeController(EscapeRoomContext context)
        {
            _context = context;
        }

        public IActionResult DetalePokoi(int id)
        {
            var room = _context.Rooms.FirstOrDefault(r => r.ID == id);

            if (room == null)
            {
                return NotFound();
            }

            ViewData["Title"] = room.RoomName;

            return View(room);
        }
    }
}

EscapeRoom/Views/Home/DashBoard.cshtml
@{
    ViewBag.Title = "Dashboard";
}
<div class="container">
<h2 class="text-left">Rezerwacje</h2>
    <table class="table table-striped table-bordered table-dashboard">
    <thead class="thead">
        <tr>
            <th>Nazwa</th>
            <th>Początek rezerwacji</th>
            <th>Koniec rezerwacji</th>
            <th>Pokój</th>
            <th>Klient</th>
            <th>Liczba osób</th>
        </tr>
    </thead>
    <tbody>
            @foreach (var reservation in ViewBag.Reservations)
            {
                if (reservation.Client != null)
                {
                    <tr>
                        <td>@reservation.Name</td>
                        <td>@reservation.ReservationStart</td>
                        <td>@reservation.ReservationEnd</td>
                        <td>@reservation.Room.RoomName</td>
                        <td>@reservation.Client.UserName</td>
                        <td>@reservation.NumberOfPeople</td>
                    </tr>
                }
            }
    </tbody>
</table>
</div>

<hr class="divider">

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <h2 class="text-left">Pokoje:</h2>
            <ul class="list-group">
                @foreach (var room in ViewBag.Rooms)
                {
                    <li class="list-group-item">@room.RoomName</li>
                }
            </ul>
        </div>
        <div class="col-lg-6">
            <h2 class="text-left">Użytkownicy:</h2>
            <ul class="list-group">
                @foreach (var user in ViewBag.Users)
                {
                    <li class="list-group-item">@user.UserName</li>
                }
            </ul>
        </div>
    </div>
</div>

EscapeRoom/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<body>
   

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-target="#myCarousel" data-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-target="#myCarousel" data-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-target="#myCarousel" data-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="bd-placeholder-img" width="100%" height="100%" src="zdjecia/carosell1.jpeg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                <div class="container">
                    <div class="carousel-caption text-start">
                        <h1>Znajdź drogę do wolności!</h1>
                        <p>Pokonuj kolejne wyzwania escape roomu, wzmacniając więzi między sobą i czerpiąc niezapomniane doznania z tej przygody.</p>
                        <p><a class="btn btn-lg btn-primary" class="nav-link" asp-area="" asp-controller="Rezerwacje" asp-action="Rezerwacje">Rezerwuj dzisiaj</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="bd-placeholder-img" width="100%" height="100%" src="zdjecia/carosell2.jpg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>Dołącz do nas</h1>
                        <p>Załóż konto i odkryj wyjątkowe oferty, łatwą rezerwację oraz dostęp do okazjonalnych promocji..</p>
                        <p><a class="btn btn-lg btn-primary" href="register.html">Stwórz konto</a></p> <!--zmienić odnośnik-->
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="bd-placeholder-img" width="100%" height="100%" src="zdjecia/cariosell3.webp" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                <div class="container">
                    <div class="carousel-caption text-end">
                        <h1>Przeżyj naszą najnowszą przygodę.</h1>
                        <p>Wciel się w rolę kosmicznego podróżnika i zmierz się z wyzwaniami, jakich świat nie widział. Czy zdołasz wrócić na Ziemię przed upływem czasu?</p>
                        <p><a class="btn btn-lg btn-primary" class="nav-link" asp-area="" asp-controller="Pokoje" asp-action="DetalePokoi" asp-route-id="1">Więcej informacji</a></p>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-target="#myCarousel" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-target="#myCarousel" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <div class="container marketing">
        <div class="row">
            <div class="col-lg-4">
                <img src="zdjecia/PokojTajemnic.jpg" alt="Pokój Tajemnic" class="bd-placeholder-img rounded-circle" width="140" height="140">
                <h2>Pokój Tajemnic</h2>
                <p>Emocjonująca gra escape room, gdzie drużyna musi rozwiązać zagadki i odkryć ukryte wskazówki, aby wydostać się z tajemniczego pokoju prze upływem czasu.</p>
                <p><a class="btn btn-secondary" class="nav-link" asp-area="" asp-controller="Pokoje" asp-action="DetalePokoi" asp-route-id="3">Więcej Infromacji &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <img src="zdjecia/LabiryntZludzen.jpg" alt="Labirynt Złudzeń" class="bd-placeholder-img rounded-circle" width="140" height="140">
                <h2>Labirynt Złudzeń</h2>
                <p>Intrygujący escape room, w którym gracze muszą pokonać szereg mylących zagadek i iluzji, aby odnaleźć wyjście z zawiłego labiryntu w wyznaczonym czasie.</p>
                <p><a class="btn btn-secondary" class="nav-link" asp-area="" asp-controller="Pokoje" asp-action="DetalePokoi" asp-route-id="2">Więcej Infromacji &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <img src="zdjecia/KosmicznaWyprawa.jpg" alt="Pokój Tajemnic" class="bd-placeholder-img rounded-circle" width="140" height="140">
                <h2>Kosmiczna Wyprawa</h2>
                <p>Ekscytujący escape room, gdzie uczestnicy muszą rozwiązać międzygwiezdne zagadki i naprawić statek kosmiczny, aby bezpiecznie wrócić na Ziemię przed upływem czasu.</p>
                <p><a class="btn btn-secondary" class="nav-link" asp-area="" asp-controller="Pokoje" asp-action="DetalePokoi" asp-route-id="1">Więcej Infromacji &raquo;</a></p>
            </div>
        </div>

        <!-- features-->
        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading">Zabierz przyjaciół do nowego wymiaru i odkryj niezwykłe emocje.</h2>
                <p class="lead">Rozwiązywanie zagadek w escape roomie to nie tylko wspaniała rozrywka, ale również idealna okazja do zbliżenia się ze znajomymi i zacieśnienia więzi. Poznajcie się na nowo, pracując razem w pokonaniu wyzwań!</p>
            </div>
            <div class="col-md-5">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="zdjecia/feature1.jpg" alt="Feature 1 Image">
            </div>
        </div>

        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-7 order-md-2">
                <h2 class="featurette-heading">Przekrocz granice wyobraźni i zrób coś niesamowitego.</h2>
                <p class="lead">Escape room to nie tylko gra - to możliwość wyjścia ze swojej strefy komfortu i wkroczenia w świat przygody. Doświadczaj niezwykłych momentów, które z pewnością na długo pozostaną w Waszej pamięci!</p>
            </div>
            <div class="col-md-5 order-md-1">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="zdjecia/feature2.jpg" alt="Feature 1 Image">
            </div>
        </div>

        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading">Przemierzaj kosmiczne strefy i odkryj swoje mocne strony.</h2>
                <p class="lead">Escape room to nie tylko rozrywka, to również szansa na lepsze poznanie siebie i swoich przyjaciół. Pracujcie razem, wspierajcie się i pokonujcie wyzwania, aby wspólnie osiągnąć sukces!</p>
            </div>
            <div class="col-md-5">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="zdjecia/feature3.jpg" alt="Feature 1 Image">
            </div>
        </div>

        <hr class="featurette-divider">
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

EscapeRoom/Views/Home/Kontakt.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

*@
@{
    Layout = "_Layout";
}

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>Godziny otwarcia</h2>
                <hr class="divider">
                <p>Poniedziałek - Czwartek: 9:00 - 20:00</p>
                <p>Piątek - Sobota: 10:00 - 23:00</p>
                <p>Niedziela: 12:00 - 21:00</p>
            </div>
            <div class="col-md-4">
                <h2>Adres</h2>
                <hr class="divider">
                <p>ul. Świętojańska 15</p>
                <p>00-001 Warszawa</p>
                <p>Polska</p>
            </div>
            <div class="col-md-4">
                <h2>Dane kontaktowe</h2>
                <hr class="divider">
                <h4>Zadzwoń do nas</h4>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                    </svg>
                    +11-111-111-111
                </p>
                <h4>Lub wyślij maila poza godzinami otwarcia</h4>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                        <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z" />
                    </svg>
                    EscapeRooms@gmail.com

                </p>
            </div>
        </div>
    </div>
</body>

EscapeRoom/Views/Home/SortedReservations.cshtml
@using EscapeRoom.Models; 

@{
    var reservations = ViewBag.Reservations as IEnumerable<Reservation>;
    var rooms = ViewBag.Rooms as IEnumerable<Room>;
}

@{
    ViewBag.Title = "Dashboard";
}

@foreach (var room in rooms)
{
    <div class=" container">
    <h2 class="text-left">Pokój @room.RoomName Rezerwacje:</h2>
    <table class="table table-striped table-bordered">

        <thead class="thead">
            <tr>
                <th>Nazwa</th>
                <th>Początek rezerwacji</th>
                <th>Koniec rezerwacji</th>
                <th>Pokój</th>
                <th>Liczba osób</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var reservation in reservations.Where(x => x.RoomID == room.ID && x.ClientID != null))
            {
                <tr>
                    <td>@reservation.Name</td>
                    <td>@reservation.ReservationStart</td>
                    <td>@reservation.ReservationEnd</td>
                    <td>@reservation.Room.RoomName</td>
                    <td>@reservation.NumberOfPeople</td>
                </tr>
            }
        </tbody>
    </table>
    </div>
    <hr class="divider">
}